### PR TITLE
Actual reproducer for Fortran + Intel + Unix Makefiles CMake touch re…

### PR DESCRIPTION
**Pull request by tylerjereddy**
@bradking Ok, I think I have it now.

I can do the following and get actual rebuilds over and over with this branch using `cmake -P rebuild.cmake`:

```
Scanning dependencies of target main
[ 25%] Building Fortran object CMakeFiles/main.dir/smod3.f90.o
[ 50%] Building Fortran object CMakeFiles/main.dir/mod.f90.o
[ 75%] Linking Fortran static library libmain.a
[100%] Built target main
```

This was incredibly hard to dissect out of the massive codebase. I'll add a few observations that may also be helpful:
- note that I've changed which file gets touched and we're now building a library instead of an executable (mostly because the exe was irrelevant to my reproducer)
- this reproducer is **super** sensitive to the Fortran type involved--for example, this diff makes the rebuilds go away on this branch:

```diff
--- a/smod4.f90
+++ b/smod4.f90
@@ -4,7 +4,7 @@ public bad_sub
 contains 
 subroutine bad_sub(var)
     type mytype
-        character(len=20) :: some_path = ''
+        integer :: some_value
     end type mytype
     type(mytype) :: var
 end subroutine bad_sub
```

### CODE REVIEW

**Comment by bradking** [comment]
For reference, the corresponding discussion in CMake's issue is [here](https://gitlab.kitware.com/cmake/cmake/-/issues/22922#note_1086132).

I can't reproduce what you observe with either GNU 11.2 or Intel 2021.3 (the latter after my one fix to CMake for `ifx`).  After the first build, `touch smod3.f90` causes only the one file to recompile and the archive to be recreated.

To eliminate differences in our environment, can you create a Dockerfile that reproduces this with gfortran?

**Comment by tylerjereddy** [comment]
@bradking As [noted](https://gitlab.kitware.com/cmake/cmake/-/issues/22922#note_1085326) in the original issue, everything works fine for `gfortran`--this is for `intel/19.0.4` and CMake `3.20.5`. Our project hasn't switched to the bleeding edge Intel oneapi stuff yet, and may not be able to for quite some time.

Isn't creating Docker infra with the proprietary Intel compilers a bit of a mess?

**Comment by bradking** [comment]
Ah, I can reproduce it with `ifort` 2021.3, thanks.  I can't reproduce it with `ifx`.

The Intel compiler is writing a new `smod3.mod` file, our `cmake_copy_f90_mod` heuristic logic [here](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.22.0/Source/cmDependsFortran.cxx#L662-688) is concluding that something in the interface changed, and the timestamp copy of the module used for dependencies is updated.  That causes consumers to rebuild.  Local debugging shows that `cmFortranStreamsDiffer` is reached but concludes the content differs.  Since the heuristic is based on an undocumented Intel-private format, it is failing in this case.

I'll post this back in the CMake issue too.

**Comment by scivision** [comment]
It seems per discussion on CMake GitLab this is quite an extensive issue with interactions from Ninja and Intel compiler internals. I'll archive the repo for long-term reference. Thanks folks.

**Pull request closed without merging**
